import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import process from "process";
import builtins from "builtin-modules";

const banner = `/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */`;

const prod = process.argv[2] === "production";

const OUT_DIR = "L:\\Vaults\\TryOpenCode\\.obsidian\\plugins\\obsidian-masonry";

const copyPlugin = {
  name: "copy-to-obsidian",
  setup(build) {
    build.onEnd(result => {
      if (result.errors.length > 0) return;
      fs.mkdirSync(OUT_DIR, { recursive: true });
      for (const f of ["main.js", "manifest.json", "styles.css"]) {
        fs.copyFileSync(f, path.join(OUT_DIR, f));
      }
      console.log(`[copy] → ${OUT_DIR}`);
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [copyPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
