/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsidianMasonryPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/masonry-view.ts
var import_obsidian2 = require("obsidian");

// src/modals.ts
var import_obsidian = require("obsidian");
var ImageViewModal = class extends import_obsidian.Modal {
  constructor(app, plugin, images, startIdx) {
    super(app);
    this.plugin = plugin;
    this.images = images;
    this.curIdx = startIdx;
  }
  onOpen() {
    var _a, _b, _c;
    const { contentEl } = this;
    contentEl.addClass("masonry-image-viewer");
    contentEl.empty();
    this.imgContainer = contentEl.createDiv({ cls: "masonry-iv-container" });
    this.imgEl = this.imgContainer.createEl("img", { cls: "masonry-iv-img" });
    this.leftNav = contentEl.createDiv({ cls: "masonry-iv-nav masonry-iv-nav-left" });
    this.leftNav.setText("\u2039");
    this.leftNav.addEventListener("click", () => this.nav(-1));
    this.rightNav = contentEl.createDiv({ cls: "masonry-iv-nav masonry-iv-nav-right" });
    this.rightNav.setText("\u203A");
    this.rightNav.addEventListener("click", () => this.nav(1));
    const bottom = contentEl.createDiv({ cls: "masonry-iv-bottom" });
    this.captionEl = bottom.createDiv({ cls: "masonry-iv-caption" });
    const closeBtn = bottom.createEl("button", { cls: "masonry-iv-close", text: "Close" });
    closeBtn.addEventListener("click", () => this.close());
    (_a = this.scope) == null ? void 0 : _a.register([], "ArrowLeft", () => {
      this.nav(-1);
      return false;
    });
    (_b = this.scope) == null ? void 0 : _b.register([], "ArrowRight", () => {
      this.nav(1);
      return false;
    });
    (_c = this.scope) == null ? void 0 : _c.register([], "Escape", () => {
      this.close();
      return false;
    });
    this.show(this.curIdx);
  }
  nav(dir) {
    const next = this.curIdx + dir;
    if (next >= 0 && next < this.images.length) {
      this.curIdx = next;
      this.show(next);
    }
  }
  show(idx) {
    const item = this.images[idx];
    if (!item)
      return;
    const file = this.app.vault.getAbstractFileByPath(item.path);
    if (!file)
      return;
    this.imgEl.setAttr("src", this.app.vault.getResourcePath(file));
    this.captionEl.setText(`${item.name}  \u2014  ${idx + 1} / ${this.images.length}`);
    this.leftNav.toggleClass("masonry-iv-hidden", idx === 0);
    this.rightNav.toggleClass("masonry-iv-hidden", idx === this.images.length - 1);
  }
  onClose() {
    this.contentEl.empty();
  }
};
var PinSelectModal = class extends import_obsidian.Modal {
  constructor(app, plugin, boards, paths) {
    super(app);
    this.plugin = plugin;
    this.boards = boards;
    this.paths = paths;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("masonry-pin-modal");
    contentEl.empty();
    contentEl.createEl("h2", { text: "Add to Pin Board" });
    const list = contentEl.createDiv({ cls: "masonry-pin-list" });
    for (const board of this.boards) {
      const row = list.createDiv({ cls: "masonry-pin-row" });
      row.createSpan({ text: board.name.replace(/\.md$/i, "") });
      const btn = row.createEl("button", { cls: "mod-cta", text: "Pin" });
      btn.addEventListener("click", async () => {
        for (const p of this.paths) {
          await this.plugin.addToPinBoard(p, board);
        }
        new import_obsidian.Notice(`Pinned ${this.paths.length} item(s) to "${board.name.replace(/\.md$/i, "")}"`);
        this.close();
      });
    }
    contentEl.createEl("hr");
    const createSec = contentEl.createDiv({ cls: "masonry-pin-create" });
    createSec.createEl("h3", { text: "Create New Board" });
    const input = createSec.createEl("input", {
      cls: "masonry-pin-name-input",
      attr: { placeholder: "Board name\u2026", type: "text" }
    });
    const createBtn = createSec.createEl("button", { text: "Create & Pin" });
    createBtn.addEventListener("click", async () => {
      const name = input.value.trim();
      if (!name) {
        new import_obsidian.Notice("Enter a name");
        return;
      }
      const file = await this.plugin.createPinBoard(name);
      if (!file)
        return;
      for (const p of this.paths) {
        await this.plugin.addToPinBoard(p, file);
      }
      new import_obsidian.Notice(`Board "${name}" created with ${this.paths.length} pin(s)`);
      this.close();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/masonry-view.ts
var VIEW_TYPE_MASONRY = "obsidian-masonry-view";
var IMAGE_EXTS = /* @__PURE__ */ new Set(["png", "jpg", "jpeg", "gif", "svg", "webp", "bmp", "ico"]);
var MasonryView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this._dragHandlers = null;
    this.currentPath = "";
    this.history = [];
    this.historyIdx = -1;
    this.items = [];
    this.selected = /* @__PURE__ */ new Set();
    this.searchQuery = "";
    this.lastSelectedEl = null;
    // board mode
    this.isBoardView = false;
    this.boardFile = null;
    this.tagFreq = /* @__PURE__ */ new Map();
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_MASONRY;
  }
  getDisplayText() {
    if (this.isBoardView && this.boardFile)
      return `Board: ${this.boardFile.name.replace(/\.md$/i, "")}`;
    return this.currentPath ? `Masonry: ${this.currentPath}` : "Masonry View";
  }
  getIcon() {
    return "grid-3x3";
  }
  async onOpen() {
    var _a, _b;
    const { containerEl: c } = this;
    c.empty();
    c.addClass("masonry-root");
    this.buildHeader(c);
    this.gridWrapper = c.createDiv({ cls: "masonry-grid-wrapper" });
    this.setupDragDrop();
    (_a = this.scope) == null ? void 0 : _a.register(["Mod", "Shift"], "Backspace", () => {
      this.deleteSelected(true);
      return false;
    });
    (_b = this.scope) == null ? void 0 : _b.register([], "Delete", (e) => {
      if (e.ctrlKey || e.metaKey)
        this.deleteSelected(true);
      else
        this.deleteSelected(false);
      return false;
    });
    if (this.currentPath)
      await this.loadFolderOrBoard(this.currentPath);
  }
  // One-time drag-drop setup — document-level capture to intercept before Obsidian
  setupDragDrop() {
    let lastDragTarget = null;
    const isMasonryTarget = (e) => {
      var _a;
      return !!((_a = e.target) == null ? void 0 : _a.closest(".masonry-grid-wrapper"));
    };
    const isNavTitle = (e) => {
      var _a, _b;
      return (_b = (_a = e.target) == null ? void 0 : _a.closest(".nav-file-title")) != null ? _b : null;
    };
    const getSrc = (e) => {
      const dt = e.dataTransfer;
      if (!dt)
        return "";
      const plain = dt.getData("text/plain");
      if (plain) {
        const txt = plain.trim();
        const obsMatch = txt.match(/obsidian:\/\/open\?.*?[&?]file=([^&]+)/);
        if (obsMatch)
          return decodeURIComponent(obsMatch[1]).replace(/\\/g, "/");
        return txt.replace(/\\/g, "/");
      }
      const uri = dt.getData("text/uri-list");
      if (uri) {
        const decoded = decodeURI(uri.replace(/^file:\/\/\//i, "").replace(/^file:\/\//i, ""));
        return decoded.trim().replace(/\\/g, "/");
      }
      return "";
    };
    const resolvePath = (raw) => {
      var _a, _b, _c;
      const tryPath = (p) => {
        const file = this.app.vault.getAbstractFileByPath(p);
        return file ? file.path : null;
      };
      let found = tryPath(raw);
      if (found)
        return found;
      if (!raw.match(/\.\w+$/)) {
        found = tryPath(raw + ".md");
        if (found)
          return found;
      }
      const vaultPath = ((_b = (_a = this.app.vault.adapter).getFullPath) == null ? void 0 : _b.call(_a, "/")) || "";
      if (vaultPath) {
        const norm = String(vaultPath).replace(/\\/g, "/").replace(/\/$/, "");
        const tryRel = (rel) => {
          const f = this.app.vault.getAbstractFileByPath(rel);
          return f ? f.path : null;
        };
        if (raw.startsWith(norm + "/")) {
          const rel = raw.slice(norm.length + 1);
          found = tryRel(rel);
          if (found)
            return found;
          if (!rel.match(/\.\w+$/)) {
            found = tryRel(rel + ".md");
            if (found)
              return found;
          }
        }
      }
      const name = ((_c = raw.split("/").pop()) == null ? void 0 : _c.split("\\").pop()) || "";
      const all = this.app.vault.getAllLoadedFiles();
      const byName = all.filter((f) => f.name === name);
      if (byName.length === 1)
        return byName[0].path;
      if (!name.match(/\.\w+$/)) {
        const exactMd = all.filter((f) => f.name === name + ".md");
        if (exactMd.length === 1)
          return exactMd[0].path;
      }
      const bySuffix = all.filter((f) => f.path.endsWith("/" + name));
      if (bySuffix.length === 1)
        return bySuffix[0].path;
      return raw;
    };
    const cleanBoardMarkers = () => {
      document.querySelectorAll(".masonry-drop-board").forEach((el) => el.removeClass("masonry-drop-board"));
      document.querySelectorAll(".masonry-drop-file-exp").forEach((el) => el.removeClass("masonry-drop-file-exp"));
    };
    const onDragOver = (e) => {
      if (isMasonryTarget(e)) {
        e.preventDefault();
        e.stopPropagation();
        const card = e.target.closest(".masonry-card");
        if (!card)
          return;
        if (lastDragTarget === card)
          return;
        if (lastDragTarget)
          lastDragTarget.removeClass("masonry-drop-board");
        lastDragTarget = null;
        const path2 = card.getAttr("data-path");
        if (!path2)
          return;
        const file2 = this.app.vault.getAbstractFileByPath(path2);
        if (file2 instanceof import_obsidian2.TFolder) {
          card.addClass("masonry-drop-board");
          lastDragTarget = card;
        } else if (file2 instanceof import_obsidian2.TFile && this.plugin.isPinBoard(file2)) {
          card.addClass("masonry-drop-board");
          lastDragTarget = card;
        }
        return;
      }
      const navTitle = isNavTitle(e);
      if (!navTitle)
        return;
      const path = navTitle.getAttr("data-path");
      if (!path)
        return;
      const file = this.app.vault.getAbstractFileByPath(path);
      if (file instanceof import_obsidian2.TFile && this.plugin.isPinBoard(file)) {
        e.preventDefault();
        e.stopPropagation();
        navTitle.addClass("masonry-drop-file-exp");
      }
    };
    const onDragLeave = () => {
      cleanBoardMarkers();
      lastDragTarget = null;
    };
    const onDrop = async (e) => {
      var _a;
      const src = getSrc(e);
      if (!src)
        return;
      const multiRaw = (_a = e.dataTransfer) == null ? void 0 : _a.getData("text/x-masonry-items");
      const rawPaths = multiRaw ? JSON.parse(multiRaw) : [src];
      const paths = rawPaths.map(resolvePath).filter(Boolean);
      if (!paths.length)
        return;
      if (isMasonryTarget(e)) {
        e.preventDefault();
        e.stopPropagation();
        cleanBoardMarkers();
        const targetCard = e.target.closest(".masonry-card");
        const targetPath2 = (targetCard == null ? void 0 : targetCard.getAttr("data-path")) || this.currentPath;
        if (!targetPath2)
          return;
        for (const p of paths)
          await this.handleDropOnFolder(p, targetPath2);
        await this.loadFolderOrBoard(this.currentPath);
        return;
      }
      const navTitle = isNavTitle(e);
      if (!navTitle)
        return;
      const targetPath = navTitle.getAttr("data-path");
      if (!targetPath)
        return;
      const file = this.app.vault.getAbstractFileByPath(targetPath);
      if (file instanceof import_obsidian2.TFile && this.plugin.isPinBoard(file)) {
        e.preventDefault();
        e.stopPropagation();
        cleanBoardMarkers();
        for (const p of paths) {
          await this.plugin.addToPinBoard(p, file);
        }
        new import_obsidian2.Notice(`Pinned to "${file.name.replace(/\.md$/i, "")}"`);
        await this.loadFolderOrBoard(this.currentPath);
      }
    };
    const opts = { capture: true };
    document.addEventListener("dragover", onDragOver, opts);
    document.addEventListener("dragleave", onDragLeave, opts);
    document.addEventListener("drop", onDrop, opts);
    this._dragHandlers = { dragover: onDragOver, dragleave: onDragLeave, drop: onDrop };
  }
  async onClose() {
    this.containerEl.empty();
    if (this._dragHandlers) {
      for (const [evt, fn] of Object.entries(this._dragHandlers)) {
        document.removeEventListener(evt, fn, { capture: true });
      }
    }
  }
  getState() {
    return { folderPath: this.currentPath, history: this.history, historyIdx: this.historyIdx, isBoardView: this.isBoardView };
  }
  async setState(state, result) {
    var _a;
    const path = state.folderPath;
    if (path) {
      this.currentPath = path;
      this.history = state.history || [];
      this.historyIdx = (_a = state.historyIdx) != null ? _a : -1;
      this.isBoardView = state.isBoardView || false;
      await this.loadFolderOrBoard(path);
    }
  }
  // ── entry point ─────────────────────────────────────────
  async loadFolderOrBoard(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file instanceof import_obsidian2.TFile && file.extension === "md" && this.plugin.isPinBoard(file)) {
      await this.loadPinBoard(file);
    } else {
      await this.loadFolder(path);
    }
  }
  // ── header ──────────────────────────────────────────────
  buildHeader(c) {
    this.headerEl = c.createDiv({ cls: "masonry-header" });
    const row1 = this.headerEl.createDiv({ cls: "masonry-hrow" });
    const nav = row1.createDiv({ cls: "masonry-nav" });
    this.backBtn = nav.createEl("button", { cls: "masonry-nav-btn", attr: { "aria-label": "Back" } });
    (0, import_obsidian2.setIcon)(this.backBtn, "arrow-left");
    this.backBtn.addEventListener("click", () => this.goBack());
    this.fwdBtn = nav.createEl("button", { cls: "masonry-nav-btn", attr: { "aria-label": "Forward" } });
    (0, import_obsidian2.setIcon)(this.fwdBtn, "arrow-right");
    this.fwdBtn.addEventListener("click", () => this.goForward());
    const sc = row1.createDiv({ cls: "masonry-search" });
    const searchIcon = sc.createSpan({ cls: "masonry-search-icon" });
    (0, import_obsidian2.setIcon)(searchIcon, "search");
    this.searchEl = sc.createEl("input", {
      cls: "masonry-search-input",
      attr: { placeholder: "Search name or tag\u2026", type: "text" }
    });
    this.searchEl.addEventListener("input", () => {
      this.searchQuery = this.searchEl.value;
      this.render();
    });
    this.searchEl.addEventListener("keydown", (e) => {
      if (e.key === "Escape") {
        this.searchEl.value = "";
        this.searchQuery = "";
        this.render();
      }
    });
    this.pathEl = row1.createDiv({ cls: "masonry-path" });
    this.editBoardBtnEl = row1.createEl("button", {
      cls: "masonry-action-btn masonry-edit-board-btn",
      attr: { "aria-label": "Edit board file" }
    });
    (0, import_obsidian2.setIcon)(this.editBoardBtnEl, "pencil");
    this.editBoardBtnEl.style.display = "none";
    this.editBoardBtnEl.addEventListener("click", () => this.editCurrentBoard());
    const actions = row1.createDiv({ cls: "masonry-actions" });
    this.tagCloudBtnEl = actions.createEl("button", {
      cls: "masonry-action-btn",
      attr: { "aria-label": "Tag cloud" }
    });
    (0, import_obsidian2.setIcon)(this.tagCloudBtnEl, "hash");
    this.tagCloudBtnEl.addEventListener("click", () => this.toggleTagCloud());
    const tagBtn = actions.createEl("button", {
      cls: "masonry-action-btn",
      attr: { "aria-label": "Assign tags" }
    });
    (0, import_obsidian2.setIcon)(tagBtn, "tag");
    tagBtn.addEventListener("click", () => this.focusTagInput());
    const pinBtn = actions.createEl("button", {
      cls: "masonry-action-btn",
      attr: { "aria-label": "Pin selected to board" }
    });
    (0, import_obsidian2.setIcon)(pinBtn, "pin");
    pinBtn.addEventListener("click", () => this.showPinModal());
    this.tagBarEl = this.headerEl.createDiv({ cls: "masonry-tag-bar" });
    this.tagBarEl.style.display = "none";
    this.tagBarEl.createSpan({ cls: "masonry-tag-label", text: "Tags: " });
    this.tagChipsEl = this.tagBarEl.createDiv({ cls: "masonry-tag-chips" });
    this.tagInputEl = this.tagBarEl.createEl("input", {
      cls: "masonry-tag-input",
      attr: { placeholder: "add tag\u2026", type: "text" }
    });
    this.tagInputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === ",") {
        e.preventDefault();
        this.addTagFromInput();
      } else if (e.key === "Backspace" && this.tagInputEl.value === "") {
        const chips = this.getCurrentChips();
        if (chips.length > 0)
          this.removeTagAndSave(chips[chips.length - 1]);
      }
    });
    this.tagCloudEl = this.headerEl.createDiv({ cls: "masonry-tag-cloud" });
    this.tagCloudEl.style.display = "none";
  }
  // ── tag: auto-save on every change ──────────────────────
  getCurrentChips() {
    const tags = [];
    this.tagChipsEl.querySelectorAll(".masonry-chip").forEach((el) => {
      const label = el.querySelector(".masonry-chip-label");
      if (label)
        tags.push(label.textContent || "");
    });
    return tags;
  }
  async addTagFromInput() {
    const raw = this.tagInputEl.value.trim();
    if (!raw)
      return;
    const parts = raw.split(",").map((s) => s.trim().replace(/^#/, "")).filter(Boolean);
    if (parts.length === 0)
      return;
    this.tagInputEl.value = "";
    for (const tag of parts) {
      await this.addSingleTag(tag);
    }
  }
  async addSingleTag(tag) {
    if (this.selected.size === 0)
      return;
    for (const p of this.selected) {
      const existing = this.plugin.getItemTags(p);
      if (existing.includes(tag))
        continue;
      await this.plugin.setItemTags(p, [...existing, tag]);
      const item = this.items.find((i) => i.path === p);
      if (item)
        item.tags = this.plugin.getItemTags(p);
    }
    this.buildTagFreq();
    this.render();
    this.renderTagChipsFromSelection();
  }
  async removeTagAndSave(tag) {
    if (this.selected.size === 0)
      return;
    for (const p of this.selected) {
      const existing = this.plugin.getItemTags(p);
      const updated = existing.filter((t) => t !== tag);
      await this.plugin.setItemTags(p, updated);
      const item = this.items.find((i) => i.path === p);
      if (item)
        item.tags = this.plugin.getItemTags(p);
    }
    this.buildTagFreq();
    this.render();
    this.renderTagChipsFromSelection();
  }
  renderTagChipsFromSelection() {
    if (this.selected.size === 0) {
      this.tagBarEl.style.display = "none";
      return;
    }
    this.tagBarEl.style.display = "flex";
    const allTags = /* @__PURE__ */ new Set();
    for (const p of this.selected) {
      for (const t of this.plugin.getItemTags(p))
        allTags.add(t);
    }
    this.tagChipsEl.empty();
    const sorted = [...allTags].sort();
    for (const tag of sorted) {
      const chip = this.tagChipsEl.createSpan({ cls: "masonry-chip" });
      chip.createSpan({ cls: "masonry-chip-label", text: `#${tag}` });
      const del = chip.createSpan({ cls: "masonry-chip-x", text: "\xD7" });
      del.addEventListener("click", (e) => {
        e.stopPropagation();
        this.removeTagAndSave(tag);
      });
    }
  }
  focusTagInput() {
    this.renderTagChipsFromSelection();
    this.tagInputEl.focus();
  }
  // ── tag cloud ───────────────────────────────────────────
  toggleTagCloud() {
    if (this.tagCloudVisible()) {
      this.tagCloudEl.style.display = "none";
    } else {
      this.buildTagCloud();
      this.tagCloudEl.style.display = "block";
      setTimeout(() => {
        const handler = (e) => {
          if (!this.tagCloudEl.contains(e.target) && e.target !== this.tagCloudBtnEl) {
            this.tagCloudEl.style.display = "none";
            document.removeEventListener("click", handler);
          }
        };
        document.addEventListener("click", handler);
      }, 0);
    }
  }
  tagCloudVisible() {
    return this.tagCloudEl.style.display !== "none";
  }
  buildTagFreq() {
    if (!this.plugin.settings.fileTags)
      return;
    this.tagFreq.clear();
    for (const item of this.items) {
      if (item.isFolder)
        continue;
      const tags = this.plugin.getItemTags(item.path);
      for (const t of tags) {
        this.tagFreq.set(t, (this.tagFreq.get(t) || 0) + 1);
      }
    }
  }
  buildTagCloud() {
    this.tagCloudEl.empty();
    this.tagCloudEl.createDiv({ cls: "masonry-tc-title", text: "Tag Cloud" });
    const list = this.tagCloudEl.createDiv({ cls: "masonry-tc-items" });
    const sorted = [...this.tagFreq.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
    if (sorted.length === 0) {
      list.createSpan({ cls: "masonry-tc-empty", text: "No tags in this folder" });
    }
    const maxFreq = sorted.length > 0 ? sorted[0][1] : 1;
    for (const [tag, freq] of sorted) {
      const el = list.createSpan({ cls: "masonry-tc-tag" });
      el.setText(`#${tag} (${freq})`);
      const scale = 0.75 + freq / maxFreq * 0.5;
      el.style.fontSize = `${scale}em`;
      el.addEventListener("click", () => {
        this.searchEl.value = `#${tag}`;
        this.searchQuery = `#${tag}`;
        this.tagCloudEl.style.display = "none";
        this.render();
      });
    }
  }
  // ── navigation ──────────────────────────────────────────
  async loadFolder(path) {
    this.isBoardView = false;
    this.boardFile = null;
    this.editBoardBtnEl.style.display = "none";
    if (this.historyIdx === -1 || this.history[this.historyIdx] !== path) {
      this.history = this.history.slice(0, this.historyIdx + 1);
      this.history.push(path);
      this.historyIdx = this.history.length - 1;
    }
    this.currentPath = path;
    this.selected.clear();
    this.tagBarEl.style.display = "none";
    this.tagCloudEl.style.display = "none";
    this.updateUI();
    const folder = this.app.vault.getAbstractFileByPath(path);
    if (!folder || !(folder instanceof import_obsidian2.TFolder)) {
      new import_obsidian2.Notice("Folder not found");
      return;
    }
    this.items = [];
    for (const child of folder.children) {
      const item = await this.toFileItem(child);
      if (item)
        this.items.push(item);
    }
    await this.enrichItems(this.items);
    this.buildTagFreq();
    this.render();
  }
  async loadPinBoard(file) {
    this.isBoardView = true;
    this.boardFile = file;
    this.editBoardBtnEl.style.display = "inline-flex";
    const boardPath = file.path;
    if (this.historyIdx === -1 || this.history[this.historyIdx] !== boardPath) {
      this.history = this.history.slice(0, this.historyIdx + 1);
      this.history.push(boardPath);
      this.historyIdx = this.history.length - 1;
    }
    this.currentPath = boardPath;
    this.selected.clear();
    this.tagBarEl.style.display = "none";
    this.tagCloudEl.style.display = "none";
    this.updateUI();
    const pins = await this.plugin.getPinBoardPins(file);
    this.items = [];
    for (const pinPath of pins) {
      const abs = this.app.vault.getAbstractFileByPath(pinPath);
      if (abs instanceof import_obsidian2.TFolder) {
        this.items.push({ path: abs.path, name: abs.name, type: "folder", isFolder: true, tags: this.plugin.getItemTags(abs.path) });
      } else if (abs instanceof import_obsidian2.TFile) {
        const item = await this.toFileItem(abs);
        if (item) {
          item.tags = this.plugin.getItemTags(abs.path);
          this.items.push(item);
        }
      }
    }
    await this.enrichItems(this.items);
    this.buildTagFreq();
    this.render();
  }
  async editCurrentBoard() {
    var _a;
    if (this.boardFile) {
      const leaf = (_a = this.app.workspace.getMostRecentLeaf()) != null ? _a : this.app.workspace.getLeaf();
      await leaf.openFile(this.boardFile);
    }
  }
  goBack() {
    if (this.historyIdx > 0) {
      this.historyIdx--;
      this.currentPath = this.history[this.historyIdx];
      this.selected.clear();
      this.updateUI();
      this.loadFolderOrBoard(this.currentPath);
    }
  }
  goForward() {
    if (this.historyIdx < this.history.length - 1) {
      this.historyIdx++;
      this.currentPath = this.history[this.historyIdx];
      this.selected.clear();
      this.updateUI();
      this.loadFolderOrBoard(this.currentPath);
    }
  }
  updateUI() {
    if (this.isBoardView && this.boardFile) {
      this.pathEl.setText(this.boardFile.name.replace(/\.md$/i, ""));
    } else {
      this.pathEl.setText(this.currentPath || "/");
    }
    this.backBtn.toggleClass("masonry-nav-disabled", this.historyIdx <= 0);
    this.fwdBtn.toggleClass("masonry-nav-disabled", this.historyIdx >= this.history.length - 1);
  }
  // ── file-item conversion ────────────────────────────────
  async toFileItem(file) {
    if (file instanceof import_obsidian2.TFolder) {
      return { path: file.path, name: file.name, type: "folder", isFolder: true, tags: this.plugin.getItemTags(file.path) };
    }
    if (!(file instanceof import_obsidian2.TFile))
      return null;
    const ext = file.extension.toLowerCase();
    const isImage = IMAGE_EXTS.has(ext);
    const type = isImage ? "image" : ext === "md" ? "note" : "other";
    return {
      path: file.path,
      name: file.name,
      type,
      isFolder: false,
      extension: ext,
      tags: this.plugin.getItemTags(file.path)
    };
  }
  async enrichItems(items) {
    await Promise.all(items.map(async (item) => {
      if (item.type === "note" && !item.notePreview) {
        item.notePreview = await this.getNotePreview(item.path);
      }
      if (item.isFolder && !item.folderThumb) {
        item.folderThumb = await this.getFolderThumb(item.path);
      }
    }));
  }
  async getNotePreview(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!file)
      return "";
    try {
      const content = await this.app.vault.read(file);
      const body = content.replace(/^---[\s\S]*?---\n*/m, "");
      const lines = body.split("\n").filter((l) => l.trim());
      let preview = lines.slice(0, 30).join("\n").trim();
      preview = preview.replace(/!\[.*?\]\(.*?\)/g, "").trim();
      if (preview.length > 2e3)
        preview = preview.slice(0, 1997) + "\u2026";
      return preview || "";
    } catch (e) {
      return "";
    }
  }
  async getFolderThumb(path) {
    const folder = this.app.vault.getAbstractFileByPath(path);
    if (!folder)
      return void 0;
    for (const child of folder.children) {
      if (child instanceof import_obsidian2.TFile && IMAGE_EXTS.has(child.extension.toLowerCase()))
        return child.path;
    }
    return void 0;
  }
  getResourcePath(filePath) {
    const file = this.app.vault.getAbstractFileByPath(filePath);
    return file ? this.app.vault.getResourcePath(file) : "";
  }
  // ── rendering ───────────────────────────────────────────
  render() {
    var _a, _b, _c, _d, _e, _f;
    this.gridWrapper.empty();
    const q = this.searchQuery.toLowerCase().trim();
    let folders = this.items.filter((i) => i.isFolder).sort((a, b) => a.name.localeCompare(b.name));
    let files = this.items.filter((i) => !i.isFolder).sort((a, b) => a.name.localeCompare(b.name));
    if (q) {
      const match = (i) => i.name.toLowerCase().includes(q) || i.tags.some((t) => t.toLowerCase().includes(q));
      folders = folders.filter(match);
      files = files.filter(match);
    }
    const gap = (_a = this.plugin.settings.itemGap) != null ? _a : 10;
    const colCount = (_b = this.plugin.settings.columnCount) != null ? _b : 4;
    const noteMinH = (_c = this.plugin.settings.noteCardMinHeight) != null ? _c : 100;
    const noteMaxH = (_d = this.plugin.settings.noteCardMaxHeight) != null ? _d : 500;
    const noteFontSize = (_e = this.plugin.settings.noteCardFontSize) != null ? _e : 14;
    const folderCount = (_f = this.plugin.settings.folderCount) != null ? _f : 8;
    this.gridWrapper.style.setProperty("--masonry-gap", `${gap}px`);
    this.gridWrapper.style.setProperty("--masonry-note-min-height", `${noteMinH + 8}px`);
    this.gridWrapper.style.setProperty("--masonry-note-max-height", `${noteMaxH + 8}px`);
    this.gridWrapper.style.setProperty("--masonry-note-font-size", `${noteFontSize}px`);
    const hasSections = [];
    const rowItems = this.isBoardView ? [] : folders;
    if (rowItems.length > 0) {
      hasSections.push("folders");
      const row = this.gridWrapper.createDiv({ cls: "masonry-folders-row" });
      row.style.setProperty("--masonry-folder-count", String(folderCount));
      row.style.gap = `${gap}px`;
      for (const item of rowItems) {
        this.createCardIn(row, item);
      }
    }
    const notes = files.filter((i) => i.type === "note");
    if (notes.length > 0) {
      hasSections.push("notes");
      const grid = this.gridWrapper.createDiv({ cls: "masonry-grid masonry-grid-notes" });
      grid.style.columnCount = String(colCount);
      grid.style.columnGap = `${gap}px`;
      grid.style.marginTop = `${gap}px`;
      for (const item of notes) {
        this.createCardIn(grid, item);
      }
    }
    const others = files.filter((i) => i.type !== "note");
    if (others.length > 0) {
      hasSections.push("others");
      const grid = this.gridWrapper.createDiv({ cls: "masonry-grid masonry-grid-others" });
      grid.style.columnCount = String(colCount);
      grid.style.columnGap = `${gap}px`;
      grid.style.marginTop = `${gap}px`;
      for (const item of others) {
        this.createCardIn(grid, item);
      }
    }
    if (hasSections.length === 0) {
      this.gridWrapper.createDiv({ cls: "masonry-empty" }).setText(q ? "No items match your search" : this.isBoardView ? "This board is empty \u2014 pin some items!" : "This folder is empty");
    }
  }
  // create a card and attach all event listeners
  createCardIn(parent, item) {
    const card = parent.createDiv({
      cls: `masonry-card ${item.isFolder ? "masonry-folder" : ""} ${this.selected.has(item.path) ? "masonry-selected" : ""}`,
      attr: { draggable: "true", "data-path": item.path }
    });
    this.buildCardContent(card, item);
    card.addEventListener("click", (e) => {
      if (e.ctrlKey || e.metaKey) {
        this.toggleSelect(item.path, card);
      } else if (e.shiftKey && this.lastSelectedEl) {
        this.rangeSelect(card);
      } else {
        this.clearSelection();
        this.selected.add(item.path);
        card.addClass("masonry-selected");
        this.lastSelectedEl = card;
      }
      this.renderTagChipsFromSelection();
    });
    card.addEventListener("dblclick", () => this.openItem(item));
    card.addEventListener("dragstart", (e) => {
      var _a, _b;
      const dragPaths = this.selected.has(item.path) && this.selected.size > 1 ? [...this.selected] : [item.path];
      (_a = e.dataTransfer) == null ? void 0 : _a.setData("text/plain", item.path);
      (_b = e.dataTransfer) == null ? void 0 : _b.setData("text/x-masonry-items", JSON.stringify(dragPaths));
      e.dataTransfer.effectAllowed = "move";
      card.addClass("masonry-dragging");
    });
    card.addEventListener("dragend", () => card.removeClass("masonry-dragging"));
    card.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      if (!this.selected.has(item.path)) {
        this.clearSelection();
        this.selected.add(item.path);
        card.addClass("masonry-selected");
      }
      this.showCtxMenu(e, item);
    });
    return card;
  }
  buildCardContent(card, item) {
    const showNames = this.plugin.settings.showFileNames;
    const showTags = this.plugin.settings.showTags;
    if (item.isFolder) {
      card.addClass("masonry-folder-card");
      const header = this.buildCardHeader(card, "folder", item.name);
      if (item.folderThumb) {
        const thumb = card.createDiv({ cls: "masonry-thumb" });
        const src = this.getResourcePath(item.folderThumb);
        if (src) {
          const img = thumb.createEl("img", { cls: "masonry-img", attr: { src, loading: "lazy" } });
        }
      }
    } else if (item.type === "note") {
      card.addClass("masonry-note-card");
      const displayName = item.extension === "md" ? item.name.replace(/\.md$/i, "") : item.name;
      this.buildCardHeader(card, "document", displayName);
      const thumb = card.createDiv({ cls: "masonry-thumb" });
      if (item.notePreview) {
        const previewEl = thumb.createDiv({ cls: "masonry-note-preview" });
        import_obsidian2.MarkdownRenderer.render(this.app, item.notePreview, previewEl, item.path, this);
      } else {
        thumb.createDiv({ cls: "masonry-note-preview masonry-note-empty", text: "\u2014 empty note \u2014" });
      }
    } else {
      const thumb = card.createDiv({ cls: "masonry-thumb" });
      if (item.type === "image") {
        const src = this.getResourcePath(item.path);
        if (src) {
          const img = thumb.createEl("img", { cls: "masonry-img", attr: { src, loading: "lazy" } });
          img.onerror = () => img.replaceWith(createDiv({ cls: "masonry-placeholder", text: "\u{1F5BC}" }));
        }
      } else {
        thumb.createDiv({ cls: "masonry-placeholder", text: "\u{1F4C4}" });
      }
      if (showNames) {
        const label = card.createDiv({ cls: "masonry-label" });
        label.setText(item.name);
      }
    }
    if (showTags && (item.type === "note" || item.tags.length > 0)) {
      const tagsEl = card.createDiv({ cls: "masonry-tags" });
      for (const t of item.tags.slice(0, 5)) {
        tagsEl.createSpan({ cls: "masonry-tag", text: `#${t}` });
      }
      if (item.tags.length > 5)
        tagsEl.createSpan({ cls: "masonry-tag-more", text: `+${item.tags.length - 5}` });
    }
  }
  buildCardHeader(card, iconId, name) {
    const header = card.createDiv({ cls: "masonry-item-header" });
    const iconEl = header.createDiv({ cls: "masonry-item-icon" });
    (0, import_obsidian2.setIcon)(iconEl, iconId);
    header.createSpan({ cls: "masonry-item-name", text: name });
    return header;
  }
  // ── selection ───────────────────────────────────────────
  clearSelection() {
    this.selected.clear();
    this.gridWrapper.querySelectorAll(".masonry-selected").forEach((el) => el.removeClass("masonry-selected"));
    this.lastSelectedEl = null;
  }
  toggleSelect(path, card) {
    if (this.selected.has(path)) {
      this.selected.delete(path);
      card.removeClass("masonry-selected");
    } else {
      this.selected.add(path);
      card.addClass("masonry-selected");
      this.lastSelectedEl = card;
    }
  }
  rangeSelect(card) {
    const allCards = Array.from(this.gridWrapper.querySelectorAll(".masonry-card"));
    const si = allCards.indexOf(this.lastSelectedEl);
    const ei = allCards.indexOf(card);
    if (si === -1 || ei === -1)
      return;
    const [lo, hi] = si < ei ? [si, ei] : [ei, si];
    for (let i = lo; i <= hi; i++) {
      const c = allCards[i];
      const p = c.getAttr("data-path");
      if (p) {
        this.selected.add(p);
        c.addClass("masonry-selected");
      }
    }
  }
  // ── item actions ────────────────────────────────────────
  async openItem(item) {
    var _a;
    if (item.isFolder) {
      await this.loadFolderOrBoard(item.path);
      return;
    }
    const file = this.app.vault.getAbstractFileByPath(item.path);
    if (!file || !(file instanceof import_obsidian2.TFile))
      return;
    if (item.type === "image") {
      const images = this.items.filter((i) => i.type === "image");
      const idx = images.findIndex((i) => i.path === item.path);
      new ImageViewModal(this.app, this.plugin, images, idx >= 0 ? idx : 0).open();
    } else {
      const leaf = (_a = this.app.workspace.getMostRecentLeaf()) != null ? _a : this.app.workspace.getLeaf();
      await leaf.openFile(file);
    }
  }
  async deleteSelected(permanent) {
    if (this.selected.size === 0)
      return;
    if (this.isBoardView && this.boardFile) {
      const removed = new Set(this.selected);
      for (const p of this.selected) {
        await this.app.fileManager.processFrontMatter(this.boardFile, (fm) => {
          if (Array.isArray(fm.pins)) {
            fm.pins = fm.pins.filter((pin) => pin !== p);
          }
        });
      }
      new import_obsidian2.Notice(`Removed ${removed.size} pin(s) from board`);
      this.selected.clear();
      await this.loadPinBoard(this.boardFile);
      return;
    }
    for (const p of this.selected) {
      const file = this.app.vault.getAbstractFileByPath(p);
      if (!file)
        continue;
      try {
        if (permanent)
          await this.app.vault.delete(file, true);
        else
          await this.app.vault.trash(file, true);
      } catch (e) {
        console.error("Failed to delete", p, e);
      }
    }
    const count = this.selected.size;
    this.selected.clear();
    this.tagBarEl.style.display = "none";
    new import_obsidian2.Notice(permanent ? `Permanently deleted ${count} item(s)` : `Moved ${count} item(s) to trash`);
    await this.loadFolderOrBoard(this.currentPath);
  }
  async pinItem(filePath) {
    this.selected.add(filePath);
    await this.showPinModal();
  }
  async showPinModal() {
    if (this.selected.size === 0) {
      new import_obsidian2.Notice("Select items first");
      return;
    }
    const boards = this.plugin.getPinBoards();
    if (boards.length === 0) {
      new import_obsidian2.Notice("No pin boards found. Right-click a folder \u2192 Create Pin Board here.");
      return;
    }
    new PinSelectModal(this.app, this.plugin, boards, [...this.selected]).open();
  }
  showCtxMenu(e, item) {
    const menu = new import_obsidian2.Menu();
    menu.addItem((i) => i.setTitle("Open").setIcon("document").onClick(() => this.openItem(item)));
    menu.addItem((i) => i.setTitle("Pin to board").setIcon("pin").onClick(async () => {
      this.selected.add(item.path);
      await this.showPinModal();
    }));
    menu.addItem((i) => i.setTitle("Assign tags").setIcon("tag").onClick(() => {
      if (!this.selected.has(item.path)) {
        this.selected.add(item.path);
      }
      this.focusTagInput();
    }));
    menu.addSeparator();
    if (this.isBoardView) {
      menu.addItem((i) => i.setTitle("Remove from board").setIcon("trash").onClick(async () => {
        this.selected.add(item.path);
        await this.deleteSelected(false);
      }));
    } else {
      menu.addItem((i) => i.setTitle("Delete").setIcon("trash").onClick(() => {
        this.selected.add(item.path);
        this.deleteSelected(false);
      }));
    }
    menu.showAtMouseEvent(e);
  }
  // ── drag & drop ─────────────────────────────────────────
  async handleDropOnFolder(srcPath, destPath) {
    const destFile = this.app.vault.getAbstractFileByPath(destPath);
    if (destFile instanceof import_obsidian2.TFile) {
      if (this.plugin.isPinBoard(destFile)) {
        await this.plugin.addToPinBoard(srcPath, destFile);
        new import_obsidian2.Notice(`Pinned to "${destFile.name.replace(/\.md$/i, "")}"`);
        return;
      }
    }
    if (destFile instanceof import_obsidian2.TFolder) {
      const srcName = srcPath.split("/").pop();
      if (!srcName)
        return;
      const srcFile = this.app.vault.getAbstractFileByPath(srcPath);
      if (!srcFile)
        return;
      try {
        await this.app.fileManager.renameFile(srcFile, `${destPath}/${srcName}`);
      } catch (e) {
        new import_obsidian2.Notice("Move failed");
      }
    }
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  masonryFolders: [],
  showFileNames: true,
  showTags: true,
  fileTags: {},
  itemGap: 10,
  columnCount: 4,
  noteCardMinHeight: 100,
  noteCardMaxHeight: 500,
  noteCardFontSize: 14,
  folderCount: 8
};
var ObsidianMasonryPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this._openingBoard = false;
    this.injectedStyleEl = null;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_MASONRY, (leaf) => new MasonryView(leaf, this));
    this.app.workspace.onLayoutReady(() => this.updatePinBoardStyles());
    this.addCommand({
      id: "open-masonry-view",
      name: "Open Masonry View for current folder",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file == null ? void 0 : file.parent) {
          if (!checking)
            this.openMasonryView(file.parent.path);
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "toggle-masonry-folder",
      name: "Toggle masonry view for current folder",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file == null ? void 0 : file.parent) {
          if (!checking)
            this.toggleMasonryFolder(file.parent.path);
          return true;
        }
        return false;
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-open", async (file) => {
        if (this._openingBoard)
          return;
        if (!file || file.extension !== "md")
          return;
        if (this.isPinBoard(file)) {
          this._openingBoard = true;
          await this.openMasonryView(file.path);
          setTimeout(() => {
            this._openingBoard = false;
          }, 500);
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian3.TFolder) {
          const isEnabled = this.settings.masonryFolders.includes(file.path);
          menu.addItem((item) => {
            item.setTitle(isEnabled ? "Disable Masonry View" : "Enable Masonry View").setIcon("grid").onClick(async () => await this.toggleMasonryFolder(file.path));
          });
          menu.addItem((item) => {
            item.setTitle("Open in Masonry View").setIcon("grid-3x3").onClick(async () => await this.openMasonryView(file.path));
          });
          menu.addSeparator();
          menu.addItem((item) => {
            item.setTitle("Create Pin Board here").setIcon("pin").onClick(async () => {
              const name = file.name + " Board";
              const board = await this.createPinBoard(name, file.path);
              if (board) {
                new import_obsidian3.Notice(`Pin board "${name}" created`);
                this._openingBoard = true;
                await this.openMasonryView(board.path);
                setTimeout(() => {
                  this._openingBoard = false;
                }, 500);
              }
            });
          });
        }
        if (file instanceof import_obsidian3.TFile) {
          menu.addItem((item) => {
            item.setTitle("Pin to board").setIcon("pin").onClick(async () => {
              const boards = this.getPinBoards();
              new PinSelectModal(this.app, this, boards, [file.path]).open();
            });
          });
        }
      })
    );
    this.registerEvent(
      this.app.metadataCache.on("resolved", () => this.updatePinBoardStyles())
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => this.handleRename(file, oldPath))
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => this.handleDelete(file))
    );
    this.addSettingTab(new MasonrySettingTab(this.app, this));
    let lastClickPath = "";
    let lastClickTime = 0;
    this.registerDomEvent(document, "click", (e) => {
      var _a;
      if (e.button !== 0)
        return;
      const content = (_a = e.target) == null ? void 0 : _a.closest(".nav-folder-title-content");
      if (!content)
        return;
      const title = content.closest(".nav-folder-title");
      if (!title)
        return;
      const path = title.getAttr("data-path");
      if (!path || !this.settings.masonryFolders.includes(path))
        return;
      const now = Date.now();
      if (path === lastClickPath && now - lastClickTime < 400) {
        lastClickPath = "";
        lastClickTime = 0;
        return;
      }
      lastClickPath = path;
      lastClickTime = now;
      e.preventDefault();
      e.stopPropagation();
      this.openMasonryView(path);
    }, true);
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_MASONRY);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async toggleMasonryFolder(path) {
    const idx = this.settings.masonryFolders.indexOf(path);
    if (idx > -1) {
      this.settings.masonryFolders.splice(idx, 1);
      new import_obsidian3.Notice(`Masonry View disabled for "${path}"`);
    } else {
      this.settings.masonryFolders.push(path);
      new import_obsidian3.Notice(`Masonry View enabled for "${path}"`);
    }
    await this.saveSettings();
    this.updatePinBoardStyles();
  }
  async openMasonryView(folderOrBoardPath) {
    const path = folderOrBoardPath || "/";
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_MASONRY);
    if (leaves.length > 0) {
      this.app.workspace.revealLeaf(leaves[0]);
      if (leaves[0].view instanceof MasonryView) {
        await leaves[0].view.loadFolderOrBoard(path);
      }
      return;
    }
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.setViewState({
      type: VIEW_TYPE_MASONRY,
      active: true,
      state: { folderPath: path }
    });
    this.app.workspace.revealLeaf(leaf);
  }
  // ── pin boards ─────────────────────────────────────────
  isPinBoard(file) {
    var _a;
    const cache = this.app.metadataCache.getFileCache(file);
    const tags = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.tags;
    return Array.isArray(tags) && tags.includes("pin-board") || typeof tags === "string" && tags === "pin-board";
  }
  getPinBoards() {
    return this.app.vault.getMarkdownFiles().filter((f) => this.isPinBoard(f));
  }
  async createPinBoard(name, folderPath) {
    const safeName = name.replace(/[\\/:*?"<>|]/g, "_");
    let fileName = `${safeName}.md`;
    let path = folderPath ? `${folderPath}/${fileName}` : fileName;
    let counter = 1;
    while (await this.app.vault.adapter.exists(path)) {
      fileName = `${safeName} ${counter}.md`;
      path = folderPath ? `${folderPath}/${fileName}` : fileName;
      counter++;
    }
    try {
      const file = await this.app.vault.create(
        path,
        `---
tags:
  - pin-board
pins: []
---

# ${name}

Your pinned items will appear here.
`
      );
      this.updatePinBoardStyles();
      return file;
    } catch (e) {
      new import_obsidian3.Notice("Failed to create pin board");
      return null;
    }
  }
  updatePinBoardStyles() {
    if (!this.injectedStyleEl) {
      this.injectedStyleEl = this.app.workspace.containerEl.doc.createElement("style");
      this.injectedStyleEl.setAttr("data-masonry-icons", "");
      document.head.appendChild(this.injectedStyleEl);
    }
    let css = "";
    const pinSvg = `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' stroke='white' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' fill='none'%3E%3Cline x1='12' y1='17' x2='12' y2='22' stroke='white'/%3E%3Cpath d='M5 17h14v-1.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V6h1a2 2 0 0 0 0-4H8a2 2 0 0 0 0 4h1v4.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24Z'/%3E%3C/svg%3E`;
    for (const b of this.getPinBoards()) {
      const safePath = b.path.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
      css += `.nav-file-title[data-path="${safePath}"] .nav-file-title-content::before{content:"";display:inline-block;width:1.2em;height:1.2em;margin-right:0.15em;vertical-align:middle;background-color:currentColor;-webkit-mask:url("${pinSvg}") no-repeat center;mask:url("${pinSvg}") no-repeat center;-webkit-mask-size:contain;mask-size:contain}`;
    }
    const gridSvg = `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E%3Crect x='3' y='3' width='8' height='8' rx='1' fill='white'/%3E%3Crect x='13' y='3' width='8' height='8' rx='1' fill='white'/%3E%3Crect x='3' y='13' width='8' height='8' rx='1' fill='white'/%3E%3Crect x='13' y='13' width='8' height='8' rx='1' fill='white'/%3E%3C/svg%3E`;
    for (const fp of this.settings.masonryFolders) {
      const safePath = fp.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
      css += `.nav-folder-title[data-path="${safePath}"] .nav-folder-title-content::before{content:"";display:inline-block;width:1.2em;height:1.2em;margin-right:0.15em;vertical-align:middle;background-color:currentColor;-webkit-mask:url("${gridSvg}") no-repeat center;mask:url("${gridSvg}") no-repeat center;-webkit-mask-size:contain;mask-size:contain}`;
    }
    this.injectedStyleEl.textContent = css;
  }
  // update pin-board pins when files/folders are renamed/moved
  async handleRename(file, oldPath) {
    const newPath = file.path;
    const boards = this.getPinBoards();
    let needRefresh = false;
    for (const board of boards) {
      let changed = false;
      await this.app.fileManager.processFrontMatter(board, (fm) => {
        if (!Array.isArray(fm.pins))
          return;
        const updated = fm.pins.map((p) => {
          if (p === oldPath) {
            changed = true;
            return newPath;
          }
          if (p.startsWith(oldPath + "/")) {
            changed = true;
            return newPath + "/" + p.slice(oldPath.length + 1);
          }
          return p;
        });
        if (changed)
          fm.pins = updated;
      });
      if (changed) {
        needRefresh = true;
        for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_MASONRY)) {
          if (leaf.view instanceof MasonryView && leaf.view.currentPath === board.path) {
            await leaf.view.loadFolderOrBoard(board.path);
          }
        }
      }
    }
    if (needRefresh)
      this.updatePinBoardStyles();
  }
  // remove deleted files/folders from all pin-board pins
  async handleDelete(file) {
    const path = file.path;
    const boards = this.getPinBoards();
    let needRefresh = false;
    for (const board of boards) {
      let changed = false;
      await this.app.fileManager.processFrontMatter(board, (fm) => {
        if (!Array.isArray(fm.pins))
          return;
        const filtered = fm.pins.filter((p) => {
          if (p === path || p.startsWith(path + "/")) {
            changed = true;
            return false;
          }
          return true;
        });
        if (changed)
          fm.pins = filtered;
      });
      if (changed) {
        needRefresh = true;
        for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_MASONRY)) {
          if (leaf.view instanceof MasonryView && leaf.view.currentPath === board.path) {
            await leaf.view.loadFolderOrBoard(board.path);
          }
        }
      }
    }
    if (needRefresh)
      this.updatePinBoardStyles();
  }
  // normalise any path (absolute, relative, name-only) to a vault-relative path
  toVaultRelativePath(p) {
    var _a, _b;
    const clean = p.replace(/\\/g, "/").trim();
    const tryPath = (path) => {
      const file = this.app.vault.getAbstractFileByPath(path);
      return file ? file.path : null;
    };
    let found = tryPath(clean);
    if (found)
      return found;
    if (!clean.match(/\.\w+$/)) {
      found = tryPath(clean + ".md");
      if (found)
        return found;
    }
    try {
      const vaultPath = ((_b = (_a = this.app.vault.adapter).getFullPath) == null ? void 0 : _b.call(_a, "/")) || "";
      const norm = String(vaultPath).replace(/\\/g, "/").replace(/\/$/, "");
      if (norm && clean.startsWith(norm + "/")) {
        const rel = clean.slice(norm.length + 1);
        found = tryPath(rel);
        if (found)
          return found;
        if (!rel.match(/\.\w+$/)) {
          found = tryPath(rel + ".md");
          if (found)
            return found;
        }
      }
    } catch (e) {
    }
    const name = clean.split("/").pop() || "";
    const all = this.app.vault.getAllLoadedFiles();
    const byName = all.filter((f) => f.name === name);
    if (byName.length === 1)
      return byName[0].path;
    if (!name.match(/\.\w+$/)) {
      const byNameMd = all.filter((f) => f.name === name + ".md");
      if (byNameMd.length === 1)
        return byNameMd[0].path;
    }
    const bySuffix = all.filter((f) => f.path.endsWith("/" + name));
    if (bySuffix.length === 1)
      return bySuffix[0].path;
    return clean;
  }
  async addToPinBoard(filePath, board) {
    const normalized = this.toVaultRelativePath(filePath);
    await this.app.fileManager.processFrontMatter(board, (fm) => {
      if (!Array.isArray(fm.pins))
        fm.pins = [];
      if (!fm.pins.includes(normalized))
        fm.pins.push(normalized);
    });
  }
  async getPinBoardPins(board) {
    const content = await this.app.vault.read(board);
    const pins = this.parsePinsFromYaml(content);
    return pins.map((p) => this.toVaultRelativePath(p));
  }
  parsePinsFromYaml(content) {
    const fmMatch = content.match(/^---\n([\s\S]*?)\n(?:---|\.\.\.)/);
    if (!fmMatch)
      return [];
    const yaml = fmMatch[1];
    const inline = yaml.match(/^pins:\s*\[(.*?)\]\s*$/m);
    if (inline)
      return inline[1].split(",").map((s) => s.trim().replace(/['"]/g, "")).filter(Boolean);
    if (/^pins:\s*$/m.test(yaml)) {
      const lines = yaml.split("\n");
      const start = lines.findIndex((l) => /^pins:\s*$/.test(l));
      if (start === -1)
        return [];
      const items = [];
      for (let i = start + 1; i < lines.length; i++) {
        const item = lines[i].match(/^\s+-\s+(.+)$/);
        if (item)
          items.push(item[1].trim().replace(/['"]/g, ""));
        else if (lines[i].trim() && !/^\s/.test(lines[i]))
          break;
      }
      return items;
    }
    const single = yaml.match(/^pins:\s+(.+)$/m);
    if (single)
      return [single[1].trim().replace(/['"]/g, "")];
    return [];
  }
  // ── tag storage (plugin data for all files) ─────────────
  getItemTags(filePath) {
    var _a, _b;
    return (_b = (_a = this.settings.fileTags) == null ? void 0 : _a[filePath]) != null ? _b : [];
  }
  async setItemTags(filePath, tags) {
    if (!this.settings.fileTags)
      this.settings.fileTags = {};
    if (tags.length === 0) {
      delete this.settings.fileTags[filePath];
    } else {
      this.settings.fileTags[filePath] = [...tags];
    }
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (file && file.extension === "md") {
      try {
        await this.app.fileManager.processFrontMatter(file, (fm) => {
          fm.tags = tags.length > 0 ? [...tags] : void 0;
        });
      } catch (e) {
      }
    }
    await this.saveSettings();
  }
};
var MasonrySettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  refreshMasonryViews() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_MASONRY)) {
      if (leaf.view instanceof MasonryView)
        leaf.view.render();
    }
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Masonry View Settings" });
    containerEl.createEl("p", {
      text: 'Right-click a folder and choose "Open in Masonry View" to browse in Pinterest-like layout.'
    });
    new import_obsidian3.Setting(containerEl).setName("Show file names under items").setDesc("Display the filename below each masonry card").addToggle(
      (t) => t.setValue(this.plugin.settings.showFileNames).onChange(async (v) => {
        this.plugin.settings.showFileNames = v;
        await this.plugin.saveSettings();
        this.refreshMasonryViews();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Show tags under items").setDesc("Display tags below each masonry card").addToggle(
      (t) => t.setValue(this.plugin.settings.showTags).onChange(async (v) => {
        this.plugin.settings.showTags = v;
        await this.plugin.saveSettings();
        this.refreshMasonryViews();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Gap between items").setDesc("Spacing between cards in pixels").addText(
      (t) => t.setValue(String(this.plugin.settings.itemGap)).onChange(async (v) => {
        const n = parseInt(v);
        if (!isNaN(n)) {
          this.plugin.settings.itemGap = n;
          await this.plugin.saveSettings();
          this.refreshMasonryViews();
        }
      }).inputEl.type = "number"
    );
    new import_obsidian3.Setting(containerEl).setName("Column count").setDesc("Number of masonry columns").addText(
      (t) => t.setValue(String(this.plugin.settings.columnCount)).onChange(async (v) => {
        const n = parseInt(v);
        if (!isNaN(n)) {
          this.plugin.settings.columnCount = n;
          await this.plugin.saveSettings();
          this.refreshMasonryViews();
        }
      }).inputEl.type = "number"
    );
    new import_obsidian3.Setting(containerEl).setName("Note card min height").setDesc("Minimum card height for notes (px)").addText(
      (t) => t.setValue(String(this.plugin.settings.noteCardMinHeight)).onChange(async (v) => {
        const n = parseInt(v);
        if (!isNaN(n)) {
          this.plugin.settings.noteCardMinHeight = n;
          await this.plugin.saveSettings();
          this.refreshMasonryViews();
        }
      }).inputEl.type = "number"
    );
    new import_obsidian3.Setting(containerEl).setName("Note card max height").setDesc("Maximum card height for notes (px) \u2014 content exceeding this is clipped").addText(
      (t) => t.setValue(String(this.plugin.settings.noteCardMaxHeight)).onChange(async (v) => {
        const n = parseInt(v);
        if (!isNaN(n)) {
          this.plugin.settings.noteCardMaxHeight = n;
          await this.plugin.saveSettings();
          this.refreshMasonryViews();
        }
      }).inputEl.type = "number"
    );
    new import_obsidian3.Setting(containerEl).setName("Note card font size").setDesc("Font size for the note preview text (px)").addText(
      (t) => t.setValue(String(this.plugin.settings.noteCardFontSize)).onChange(async (v) => {
        const n = parseInt(v);
        if (!isNaN(n)) {
          this.plugin.settings.noteCardFontSize = n;
          await this.plugin.saveSettings();
          this.refreshMasonryViews();
        }
      }).inputEl.type = "number"
    );
    new import_obsidian3.Setting(containerEl).setName("Folders per row").setDesc("Number of folder cards in a single row").addText(
      (t) => t.setValue(String(this.plugin.settings.folderCount)).onChange(async (v) => {
        const n = parseInt(v);
        if (!isNaN(n) && n > 0) {
          this.plugin.settings.folderCount = n;
          await this.plugin.saveSettings();
          this.refreshMasonryViews();
        }
      }).inputEl.type = "number"
    );
    containerEl.createEl("h3", { text: "Masonry-enabled folders" });
    const list = containerEl.createEl("ul");
    if (this.plugin.settings.masonryFolders.length === 0) {
      list.createEl("li", { text: "None" });
    } else {
      for (const p of this.plugin.settings.masonryFolders) {
        list.createEl("li", { text: p });
      }
    }
    containerEl.createEl("hr");
    new import_obsidian3.Setting(containerEl).setName("Clear all folder assignments").setDesc("Remove masonry view from all folders").addButton(
      (btn) => btn.setButtonText("Clear All").setWarning().onClick(async () => {
        this.plugin.settings.masonryFolders = [];
        await this.plugin.saveSettings();
        this.display();
        new import_obsidian3.Notice("Cleared all masonry folder settings");
      })
    );
  }
};
